CREATE TABLE [dbo].[Products] (
    [Id]                   INT             IDENTITY (1, 1) NOT NULL,
    [Admin]                NVARCHAR (MAX)  NULL,
    [Name]                 NVARCHAR (MAX)  NULL,
    [Description]          NVARCHAR (MAX)  NULL,
    [Details]              NVARCHAR (MAX)  NULL,
    [Specification]        NVARCHAR (MAX)  NULL,
    [Slug]                 NVARCHAR (450)  NOT NULL,
    [Active]               BIT             NOT NULL,
    [CategoryId]           INT             NULL,
    [Rating]               INT             NOT NULL,
    [OldPrice]             DECIMAL (18, 2) NOT NULL,
    [NewPrice]             DECIMAL (18, 2) NOT NULL,
    [Quantity]             DECIMAL (18, 2) NOT NULL,
    [IsOffer]              BIT             NOT NULL,
    [Offer]                DECIMAL (18, 2) NOT NULL,
    [MetaTitle]            NVARCHAR (MAX)  NULL,
    [MetaKeywords]         NVARCHAR (MAX)  NULL,
    [MetaDescription]      NVARCHAR (MAX)  NULL,
    [Image]                NVARCHAR (MAX)  NULL,
    [CountView]            INT             NOT NULL,
    [CountSale]            INT             NOT NULL,
    [Position]             INT             NOT NULL DEFAULT 0,
    [MainCharacteristics]  NVARCHAR (MAX)  NULL,
    [TechnicalDescription] NVARCHAR (MAX)  NULL,
    [General]              NVARCHAR (MAX)  NULL,
    [Garantie]             NVARCHAR (MAX)  NULL,
    [VenduWith]            NVARCHAR (MAX)  NULL,
    [InsertDate]           DATETIME2 (7)   NOT NULL,
    [LastUpdate]           DATETIME2 (7)   NOT NULL,
    [ShortName]            NVARCHAR(50) NOT NULL DEFAULT '',
    [SearchTerms] NVARCHAR(MAX) NOT NULL DEFAULT '', 
    CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UXC_Product_Slug] UNIQUE NONCLUSTERED ([Slug] ASC),
    CONSTRAINT [FK_Product_Category] FOREIGN KEY (CategoryId) REFERENCES Categories ([Id])
);



